on: [push]
name: Check

jobs:
  Check:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: deepakbedase123/devops_machininfo_githubactions_ecr@master
      - name: Build image
        id: DockerBuild
        env:
          imagetag: ${{ github.sha }}
          ecr_repo: devops_machineinfo_prod_deepak
          ecr_registry: ${{ ecr_registry }}
        run: 
          docker build -t $ecr_registry/$ecr_repo::$imagetag .        
      - name: Push to ECR
        id: PushToECR
        env:
          imagetag: ${{ github.sha }}
          ecr_repo: devops_machineinfo_prod_deepak
          ecr_registry: ${{ ecr_registry }}
        run:
          docker push $ecr_registry/$ecr_repo::$imagetag
     
