on: [push]
name: Check

jobs:
  Check:
    name: xyz
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        id: DockerBuild
        env:
          imagetag: ${{ github.sha }}
          ecr_repo: devops_machineinfo_prod_deepak
          
        run: 
          docker build  .        
      - name: Push to ECR
        id: PushToECR
        env:
          imagetag: ${{ github.sha }}
          ecr_repo: devops_machineinfo_prod_deepak
        
        run:
          docker push 543816070942.dkr.ecr.us-east-1.amazonaws.com/$ecr_repo::$imagetag
     
